spring.application.name=JobApplication


#H2 database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.hibernate.ddl-auto=create-drop

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/JobApp
spring.datasource.username=admin
spring.datasource.password=postgresql
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS

#to endpoint name,description add by us
info.app.name = JobApplication
info.app.description=Job build by Ramkrishna
info.app.version=1.0.0
info.app.date=25/05/26

management.info.env.enabled=true
management.endpoint.shutdown.enabled=true
server.shutdown=GRACEFUL
#A graceful shutdown is a controlled process of stopping a
# computer system, server, or application. Instead of shutting
# down abruptly, the system rejects new requests, safely finishes
# ongoing tasks, saves state, and frees up resources, ensuring zero
# data loss and minimal user disruption



